"""插件常量。"""

from __future__ import annotations

PLUGIN_ID = "astrbot_plugin_goal_tracker"

MODE_CHECKIN = "checkin"
MODE_TIMER = "timer"
VALID_MODES = {MODE_CHECKIN, MODE_TIMER}
MODE_LABELS = {MODE_CHECKIN: "每日打卡", MODE_TIMER: "每日计时"}

DEFAULT_MAX_RECORDS = 5000
MIN_MAX_RECORDS = 100
MAX_MAX_RECORDS = 100000

MAX_GOALS_PER_USER = 100
MAX_TITLE_LENGTH = 80
MAX_DESCRIPTION_LENGTH = 300
MAX_NOTE_LENGTH = 300
MAX_DAILY_CHECKINS = 10000
MAX_DURATION_MINUTES = 24 * 60
BACKFILL_MAX_DAYS = 30
PENDING_IMAGE_HOURS = 24
